
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: tunnelbindings.networking.cfargotunnel.com
spec:
  group: networking.cfargotunnel.com
  names:
    kind: TunnelBinding
    listKind: TunnelBindingList
    plural: tunnelbindings
    singular: tunnelbinding
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.hostnames
      name: FQDNs
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TunnelBinding is the Schema for the tunnelbindings API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          status:
            description: TunnelBindingStatus defines the observed state of TunnelBinding
            properties:
              hostnames:
                description: To show on the kubectl cli
                type: string
              services:
                items:
                  description: ServiceInfo stores the Hostname and Target for each
                    service
                  properties:
                    hostname:
                      description: FQDN of the service
                      type: string
                    target:
                      description: Target for cloudflared
                      type: string
                  required:
                  - hostname
                  - target
                  type: object
                type: array
            required:
            - hostnames
            - services
            type: object
          subjects:
            items:
              description: TunnelBindingSubject defines the subject TunnelBinding
                connects to the Tunnel
              properties:
                kind:
                  default: Service
                  description: Kind can be Service
                  type: string
                name:
                  type: string
                spec:
                  properties:
                    caPool:
                      description: CaPool trusts the CA certificate referenced by
                        the key in the secret specified in tunnel.spec.originCaPool.
                        tls.crt is trusted globally and does not need to be specified.
                        Only useful if the protocol is HTTPS.
                      type: string
                    fqdn:
                      description: Fqdn specifies the DNS name to access this service
                        from. Defaults to the service.metadata.name + tunnel.spec.domain.
                        If specifying this, make sure to use the same domain that
                        the tunnel belongs to. This is not validated and used as provided
                      type: string
                    noTlsVerify:
                      default: false
                      description: NoTlsVerify sisables TLS verification for this
                        service. Only useful if the protocol is HTTPS.
                      type: boolean
                    protocol:
                      description: Protocol specifies the protocol for the service.
                        Should be one of http, https, tcp, udp, ssh or rdp. Defaults
                        to http, with the exceptions of https for 443, smb for 139
                        and 445, rdp for 3389 and ssh for 22 if the service has a
                        TCP port. The only available option for a UDP port is udp,
                        which is default.
                      type: string
                    target:
                      description: Target specified where the tunnel should proxy
                        to. Defaults to the form of <protocol>://<service.metadata.name>.<service.metadata.namespace>.svc:<port>
                      type: string
                  type: object
              required:
              - name
              type: object
            type: array
          tunnelRef:
            description: TunnelRef defines the Tunnel TunnelBinding connects to
            properties:
              disableDNSUpdates:
                description: DisableDNSUpdates disables the DNS updates on Cloudflare,
                  just managing the configs. Assumes the DNS entries are manually
                  added.
                type: boolean
              kind:
                description: Kind can be Tunnel or ClusterTunnel
                type: string
              name:
                description: Name of the tunnel resource
                type: string
            required:
            - kind
            - name
            type: object
        required:
        - subjects
        - tunnelRef
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
